services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    ports:
      - "${DJANGO_PORT}:8000"
    command: sh /entrypoint.sh postgres:5432
    env_file:
      - ../.env
    depends_on:
      - postgres
    volumes:
      - ..:/app

  postgres:
    image: postgres:13
    ports:
      - "5434:5432"  # Измененный порт для решения конфликта
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


